from .AdminAddAndEditProductPage import AdminAddAndEditProductPage
from .AdminLoginPage import AdminLoginPage
from .AdminProductsPage import AdminProductsPage
from .BasePage import BasePage
from .CatalogPage import CatalogPage
from .MainPage import MainPage
from .ProductPage import ProductPage
from .SearchResultsPage import SearchResultsPage
from .ComparisonPage import ComparisonPage